//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.ServiceCAR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCAR.ICarService")]
    public interface ICarService {
        
        // CODEGEN: Контракт генерации сообщений с операцией SetCar не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/SetCar", ReplyAction="http://tempuri.org/ICarService/SetCarResponse")]
        WebClient.ServiceCAR.SetCarResponse SetCar(WebClient.ServiceCAR.CarInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/SetCar", ReplyAction="http://tempuri.org/ICarService/SetCarResponse")]
        System.Threading.Tasks.Task<WebClient.ServiceCAR.SetCarResponse> SetCarAsync(WebClient.ServiceCAR.CarInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetCar", ReplyAction="http://tempuri.org/ICarService/GetCarResponse")]
        WebClient.ServiceCAR.CarInfo GetCar(WebClient.ServiceCAR.CarRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetCar", ReplyAction="http://tempuri.org/ICarService/GetCarResponse")]
        System.Threading.Tasks.Task<WebClient.ServiceCAR.CarInfo> GetCarAsync(WebClient.ServiceCAR.CarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarInfoWrapper", WrapperNamespace="http://inclickDomain.com", IsWrapped=true)]
    public partial class CarInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Vendor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int Year;
        
        public CarInfo() {
        }
        
        public CarInfo(int Id, string Model, string Vendor, int Year) {
            this.Id = Id;
            this.Model = Model;
            this.Vendor = Vendor;
            this.Year = Year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetCarResponse {
        
        public SetCarResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CarRequest", WrapperNamespace="http://inclickDomain.com", IsWrapped=true)]
    public partial class CarRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://inclickDomain.com")]
        public string LicenseKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://inclickDomain.com", Order=0)]
        public int Id;
        
        public CarRequest() {
        }
        
        public CarRequest(string LicenseKey, int Id) {
            this.LicenseKey = LicenseKey;
            this.Id = Id;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarServiceChannel : WebClient.ServiceCAR.ICarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceClient : System.ServiceModel.ClientBase<WebClient.ServiceCAR.ICarService>, WebClient.ServiceCAR.ICarService {
        
        public CarServiceClient() {
        }
        
        public CarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceCAR.SetCarResponse WebClient.ServiceCAR.ICarService.SetCar(WebClient.ServiceCAR.CarInfo request) {
            return base.Channel.SetCar(request);
        }
        
        public void SetCar(int Id, string Model, string Vendor, int Year) {
            WebClient.ServiceCAR.CarInfo inValue = new WebClient.ServiceCAR.CarInfo();
            inValue.Id = Id;
            inValue.Model = Model;
            inValue.Vendor = Vendor;
            inValue.Year = Year;
            WebClient.ServiceCAR.SetCarResponse retVal = ((WebClient.ServiceCAR.ICarService)(this)).SetCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClient.ServiceCAR.SetCarResponse> WebClient.ServiceCAR.ICarService.SetCarAsync(WebClient.ServiceCAR.CarInfo request) {
            return base.Channel.SetCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceCAR.SetCarResponse> SetCarAsync(int Id, string Model, string Vendor, int Year) {
            WebClient.ServiceCAR.CarInfo inValue = new WebClient.ServiceCAR.CarInfo();
            inValue.Id = Id;
            inValue.Model = Model;
            inValue.Vendor = Vendor;
            inValue.Year = Year;
            return ((WebClient.ServiceCAR.ICarService)(this)).SetCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClient.ServiceCAR.CarInfo WebClient.ServiceCAR.ICarService.GetCar(WebClient.ServiceCAR.CarRequest request) {
            return base.Channel.GetCar(request);
        }
        
        public string GetCar(string LicenseKey, ref int Id, out string Vendor, out int Year) {
            WebClient.ServiceCAR.CarRequest inValue = new WebClient.ServiceCAR.CarRequest();
            inValue.LicenseKey = LicenseKey;
            inValue.Id = Id;
            WebClient.ServiceCAR.CarInfo retVal = ((WebClient.ServiceCAR.ICarService)(this)).GetCar(inValue);
            Id = retVal.Id;
            Vendor = retVal.Vendor;
            Year = retVal.Year;
            return retVal.Model;
        }
        
        public System.Threading.Tasks.Task<WebClient.ServiceCAR.CarInfo> GetCarAsync(WebClient.ServiceCAR.CarRequest request) {
            return base.Channel.GetCarAsync(request);
        }
    }
}
